import {beforeEach,it,expect,vi} from 'vitest';
import {POST as profile} from '../../app/api/account/profile/route';
import {GET as summary} from '../../app/api/account/summary/route';
import {POST as signout} from '../../app/api/auth/signout/route';
const m=vi.hoisted(()=>({getUser:vi.fn(),signOut:vi.fn(),from:vi.fn(),update:vi.fn(),eq:vi.fn(),select:vi.fn(),single:vi.fn(),maybeSingle:vi.fn()}));
vi.mock('../../app/lib/supabase/server',()=>({createSupabaseServerClient:async()=>({auth:m,from:m.from})}));
beforeEach(()=>{vi.resetAllMocks();m.getUser.mockResolvedValue({data:{user:{id:'owner',user_metadata:{role:'admin'}}},error:null});m.signOut.mockResolvedValue({error:null});m.from.mockReturnValue(m);m.update.mockReturnValue(m);m.eq.mockReturnValue(m);m.select.mockReturnValue(m);m.single.mockResolvedValue({data:{display_name:'Yeni Ad'},error:null});m.maybeSingle.mockResolvedValue({data:{display_name:'Ad'},error:null});});
function req(body:unknown={},owner='owner',origin='http://localhost:3000'){return new Request('http://localhost:3000/api/account/profile',{method:'POST',headers:{origin,'content-type':'application/json','x-expected-user-id':owner},body:JSON.stringify(body)});}
it('updates only owner display name with a verified returned row',async()=>{const r=await profile(req({displayName:' Yeni Ad '}));expect(r.status).toBe(200);expect(m.eq).toHaveBeenCalledWith('user_id','owner');expect(m.update).toHaveBeenCalledWith({display_name:'Yeni Ad',updated_at:expect.any(String)});expect(r.headers.get('cache-control')).toBe('no-store');});
it.each([{displayName:'x'},{displayName:'A'.repeat(121)},{displayName:'Ad',role:'admin'},{displayName:'Ad',userId:'other'}])('rejects invalid profile payload %j',async body=>{expect((await profile(req(body))).status).toBe(400);expect(m.update).not.toHaveBeenCalled();});
it('rejects swapped owner and cross origin',async()=>{expect((await profile(req({displayName:'Ad'},'other'))).status).toBe(409);expect((await profile(req({displayName:'Ad'},'owner','https://other.test'))).status).toBe(403);expect(m.update).not.toHaveBeenCalled();});
it('does not update without authentication',async()=>{m.getUser.mockResolvedValue({data:{user:null},error:null});expect((await profile(req({displayName:'Ad'}))).status).toBe(401);});
it('does not pretend a missing profile was saved',async()=>{m.single.mockResolvedValue({data:null,error:null});expect((await profile(req({displayName:'Ad'}))).status).toBe(502);});
it('hides update provider errors',async()=>{m.single.mockResolvedValue({data:null,error:{message:'private SQL'}});expect(await (await profile(req({displayName:'Ad'}))).text()).not.toContain('private SQL');});
it('reads navigation roles from DB, not metadata',async()=>{m.eq.mockImplementation(()=>({data:[{role:'customer'}],error:null,maybeSingle:m.maybeSingle}));const r=await summary();expect(await r.json()).toEqual({user:{id:'owner',name:'Ad',roles:['customer']}});});
it('distinguishes anonymous from provider failure',async()=>{m.getUser.mockResolvedValue({data:{user:null},error:{name:'AuthSessionMissingError'}});expect(await (await summary()).json()).toEqual({user:null});m.getUser.mockResolvedValue({data:{user:null},error:{name:'AuthRetryableFetchError'}});expect((await summary()).status).toBe(503);});
it('uses local logout and does not return success on provider failure',async()=>{m.signOut.mockResolvedValue({error:{message:'private detail'}});const r=await signout(req());expect(r.status).toBe(502);expect(await r.text()).not.toContain('private detail');expect(m.signOut).toHaveBeenCalledWith({scope:'local'});});
it('rejects cross origin logout',async()=>{expect((await signout(req({},'owner','https://other.test'))).status).toBe(403);expect(m.signOut).not.toHaveBeenCalled();});
it('returns confirmed logout success without caching',async()=>{const r=await signout(req());expect(r.status).toBe(200);expect(await r.json()).toMatchObject({success:true});expect(r.headers.get('cache-control')).toBe('no-store');});
