'use client';

import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {useState} from 'react';

type WorkEntry={id:string;kind:string;caption:string|null;moderation_status:string;customer_publication_consent:boolean;created_at:string;signedUrl:string|null};
type Review={id:string;rating:number;comment:string|null;moderation_status:string;created_at:string}|null;
type Certificate={certificate_number:string;issued_at:string;warranty_ends_at:string|null;scope_snapshot:Record<string,unknown>}|null;
type Dispute={id:string;category:string;description:string;status:string;resolution:string|null;created_at:string};
type Props={jobId:string;role:'customer'|'tradesperson'|'admin';status:string;entries:WorkEntry[];review:Review;certificate:Certificate;disputes:Dispute[]};
const kindLabels:Record<string,string>={before:'İş öncesi',progress:'İş sırasında',material:'Malzeme',after:'İş sonrası'};
const statusLabels:Record<string,string>={pending:'İncelemede',approved:'Yayına uygun',rejected:'Reddedildi',hidden:'Gizlendi',open:'Açık',under_review:'İnceleniyor',awaiting_evidence:'Kanıt bekleniyor',resolved:'Çözüldü',dismissed:'Kapatıldı'};

export default function JobTrustCenter(props:Props){
  const router=useRouter();const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [rating,setRating]=useState(5);const [comment,setComment]=useState('');const [category,setCategory]=useState('quality');const [description,setDescription]=useState('');
  async function jsonPost(url:string,body:unknown,key:string){setBusy(key);setNotice('');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string};setBusy('');if(!response.ok){setNotice(result.error??'İşlem tamamlanamadı.');return false;}router.refresh();return true;}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy('media');setNotice('');const form=new FormData(event.currentTarget);const response=await fetch(`/api/jobs/${props.jobId}/work-log`,{method:'POST',body:form});const result=await response.json() as {error?:string};setBusy('');if(!response.ok)return setNotice(result.error??'Görsel yüklenemedi.');event.currentTarget.reset();router.refresh();}
  async function submitReview(event:React.FormEvent){event.preventDefault();if(await jsonPost(`/api/jobs/${props.jobId}/reviews`,{rating,comment:comment||undefined},'review'))setComment('');}
  async function openDispute(event:React.FormEvent){event.preventDefault();if(await jsonPost(`/api/jobs/${props.jobId}/disputes`,{category,description},'dispute'))setDescription('');}
  return <section className="trust-center">
    <header className="trust-center-header"><div><span>GÜVEN MERKEZİ</span><h2>İşin kanıtı, kabulü ve güvencesi</h2><p>Her kayıt bu işe bağlıdır; yayınlanacak görseller ayrıca izin ve moderasyon kontrolünden geçer.</p></div><div className="trust-mark" aria-hidden="true"><i/><i/><i/><i/></div></header>
    <div className="trust-grid">
      <section className="job-panel trust-wide"><div className="panel-heading"><div><span>01 · İŞ GÜNLÜĞÜ</span><h3>Öncesinden sonrasına</h3></div><b>{props.entries.length} kayıt</b></div><div className="work-log-grid">{props.entries.map(entry=><article key={entry.id}>{entry.signedUrl?<Image unoptimized width={480} height={360} alt={entry.caption||kindLabels[entry.kind]} src={entry.signedUrl}/>:<div className="media-placeholder">Görsel korunuyor</div>}<div><span>{kindLabels[entry.kind]??entry.kind}</span><b>{entry.caption||'Açıklama eklenmedi'}</b><small>{statusLabels[entry.moderation_status]??entry.moderation_status} · {entry.customer_publication_consent?'Yayın izni var':'Yalnız katılımcılar'}</small></div></article>)}</div>{props.status!=='cancelled'&&<form className="work-log-form" onSubmit={upload}><select name="kind" required defaultValue="before"><option value="before">İş öncesi</option><option value="progress">İş sırasında</option><option value="material">Malzeme</option><option value="after">İş sonrası</option></select><input name="caption" maxLength={500} placeholder="Bu görselde neyi belgelediniz?"/><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/><label><input name="customerPublicationConsent" type="checkbox" value="true"/> Kamusal profilde yayınlanmasına izin veriyorum</label><button disabled={busy==='media'}>{busy==='media'?'Yükleniyor…':'Günlüğe ekle'}</button></form>}</section>
      <section className="job-panel"><div className="panel-heading"><div><span>02 · DEĞERLENDİRME</span><h3>Doğrulanmış iş yorumu</h3></div></div>{props.review?<article className="review-card"><div aria-label={`${props.review.rating} yıldız`}>{'★'.repeat(props.review.rating)}{'☆'.repeat(5-props.review.rating)}</div><p>{props.review.comment||'Yorum yazılmadı.'}</p><small>{statusLabels[props.review.moderation_status]??props.review.moderation_status}</small></article>:props.role==='customer'&&props.status==='completed'?<form className="review-form" onSubmit={submitReview}><div className="rating-input" aria-label="Puan">{[1,2,3,4,5].map(value=><button aria-label={`${value} yıldız`} className={value<=rating?'active':''} key={value} onClick={()=>setRating(value)} type="button">★</button>)}</div><textarea minLength={10} maxLength={2000} value={comment} onChange={event=>setComment(event.target.value)} placeholder="İşçilik, iletişim ve zamanlama deneyiminizi anlatın"/><button disabled={busy==='review'}>Değerlendirmeyi gönder</button></form>:<p className="trust-empty">Değerlendirme, müşteri işi tamamladıktan sonra açılır.</p>}</section>
      <section className="job-panel certificate-panel"><div className="panel-heading"><div><span>03 · İŞÇİLİK BELGESİ</span><h3>Dijital güvence</h3></div></div>{props.certificate?<article className="certificate"><span>ANKARA USTA</span><strong>{props.certificate.certificate_number}</strong><p>Düzenlenme: {new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(props.certificate.issued_at))}</p><p>{props.certificate.warranty_ends_at?`Garanti sonu: ${new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(props.certificate.warranty_ends_at))}`:'Garanti süresi belirtilmedi'}</p><button onClick={()=>window.print()} type="button">Belgeyi yazdır</button></article>:<p className="trust-empty">Belge, müşteri işi kabul ettiğinde otomatik hazırlanır.</p>}</section>
      <section className="job-panel trust-wide"><div className="panel-heading"><div><span>04 · UYUŞMAZLIK</span><h3>Şeffaf çözüm kaydı</h3></div><b>{props.disputes.filter(item=>!['resolved','dismissed'].includes(item.status)).length} aktif</b></div>{props.disputes.map(item=><article className="dispute-row" key={item.id}><div><span>{statusLabels[item.status]??item.status}</span><b>{item.category}</b><p>{item.description}</p>{item.resolution&&<small>Çözüm: {item.resolution}</small>}</div><time>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(item.created_at))}</time></article>)}{!props.disputes.some(item=>!['resolved','dismissed'].includes(item.status))&&<form className="dispute-form" onSubmit={openDispute}><select value={category} onChange={event=>setCategory(event.target.value)}><option value="quality">İşçilik kalitesi</option><option value="scope">Kapsam uyuşmazlığı</option><option value="payment">Ödeme</option><option value="conduct">Davranış</option><option value="damage">Hasar</option><option value="other">Diğer</option></select><textarea required minLength={20} maxLength={4000} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Durumu somut olaylar ve tarihlerle açıklayın"/><button disabled={busy==='dispute'}>Uyuşmazlık kaydı aç</button></form>}</section>
    </div>{notice&&<p className="account-message">{notice}</p>}
  </section>;
}
